"""empty message

Revision ID: 1b3a735955bf
Revises: 0acb0ef8ceca
Create Date: 2025-05-28 22:32:41.149474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3a735955bf'
down_revision = '0acb0ef8ceca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_questions', sa.Integer(), nullable=False))
        batch_op.drop_column('how_many_questions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('how_many_questions', sa.INTEGER(), nullable=False))
        batch_op.drop_column('count_questions')

    # ### end Alembic commands ###
